// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type ChatCompletionRequest struct {
	Model       string    `json:"model"`
	Messages    []Message `json:"messages"`
	Stream      bool      `json:"stream,optional"`
	Temperature float64   `json:"temperature,optional"`
	MaxTokens   int       `json:"max_tokens,optional"`
	ClientId    string    `json:"client_id,optional"`
	ProjectPath string    `json:"project_path,optional"`
}

type ChatCompletionResponse struct {
	Id      string   `json:"id"`
	Object  string   `json:"object"`
	Created int64    `json:"created"`
	Model   string   `json:"model"`
	Choices []Choice `json:"choices"`
	Usage   Usage    `json:"usage,optional"`
}

type Choice struct {
	Index        int     `json:"index"`
	Message      Message `json:"message,optional"`
	Delta        Message `json:"delta,optional"`
	FinishReason string  `json:"finish_reason,optional"`
}

type Message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type Usage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}
